services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/Gateway.API/Dockerfile
    ports:
      - "5002:8080"
      - "5003:8081"
    depends_on:
      - api

